omg: 1
info:
  version: 0.0.1
  title: MinimalMicroservice
  description: A minimal microservice
  license:
    name: MIT
    url: example.com/MIT
  contact:
    name: John Doe
    url: example.com/minimal
    email: minimal@example.com
environment:
 ENV_VAR:
  type: string
  pattern: '.*'
  required: true
  help: env var help
